FROM nickgryg/alpine-pandas:3.7.10


ENV LANG C.UTF-8



RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.8/main" >> /etc/apk/repositories \
  && apk add --update \
              bash \
	      wget \
              build-base \
              git \
              libffi-dev \
              musl \
              runit \
              postgresql-client \
              postgresql-dev \
              tmux \
              xmlsec \ 
  && pip install --upgrade pip 


RUN cd /usr/bin \
  && ln -sf easy_install-3.7 easy_install \
  && ln -sf python3.7 python \
  && ln -sf python3.7-config python-config \
  && ln -sf pip3.7 pip

# Copy and install our requirements first, so they can be cached
COPY ./plgx-esp-ui/requirements/prod.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

# Add our application to the container
COPY ./plgx-esp-ui/. /src/plgx-esp-ui/
COPY ./resources/. /src/plgx-esp-ui/resources/
COPY ./resources/. /src/plgx-esp-ui/resources/ 

RUN chmod a+x /src/plgx-esp-ui/docker-entrypoint.sh
#RUN mkdir -p /var/log/esp-ui

ENTRYPOINT ["/src/plgx-esp-ui/docker-entrypoint.sh"]


