apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: aws-efs
  labels:
    {{- include "eiq-er-shared.labels" . | nindent 4 }}
  name: {{ include "eiq-er-shared.fullname" . }}-carves
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi