"""empty message

Revision ID: 196ab1c322d8
Revises: 4637ab4272d6
Create Date: 2022-01-08 11:06:24.557851

"""

# revision identifiers, used by Alembic.
revision = '196ab1c322d8'
down_revision = '4637ab4272d6'

from alembic import op
import sqlalchemy as sa
import polylogyx.db.database
import flask_authorize

from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('alerts', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('alerts', sa.Column('verdict', sa.Integer(), nullable=True))
    op.execute('update alerts set verdict=0;')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('alerts', 'verdict')
    op.drop_column('alerts', 'comment')

    # ### end Alembic commands ###
