"""empty message

Revision ID: 20676a265f97
Revises: c51801ce4134
Create Date: 2021-02-04 09:56:26.129012

"""

# revision identifiers, used by Alembic.
revision = "20676a265f97"
down_revision = "c51801ce4134"

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "download_csv_export",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("download_csv_export")
    # ### end Alembic commands ###
