"""empty message

Revision ID: 2eea3c907781
Revises: 196ab1c322d8
Create Date: 2022-01-11 22:22:05.335652

"""

# revision identifiers, used by Alembic.
revision = '2eea3c907781'
down_revision = '196ab1c322d8'

from alembic import op
import sqlalchemy as sa
import polylogyx.db.database
import flask_authorize

from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('container_metrics')
    # ### end Alembic commands ###
