"""empty message

Revision ID: 5a2508fb7404
Revises: 20676a265f97
Create Date: 2021-04-21 10:20:12.925461

"""

# revision identifiers, used by Alembic.
revision = "5a2508fb7404"
down_revision = "20676a265f97"

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "released_agent_versions", sa.Column("arch", sa.String(), nullable=True)
    )
    op.add_column(
        "released_agent_versions",
        sa.Column("osquery_hash_md5", sa.String(), nullable=True),
    )
    op.add_column(
        "released_agent_versions", sa.Column("cpt_version", sa.String(), nullable=True)
    )
    op.add_column(
        "released_agent_versions", sa.Column("cpt_hash_md5", sa.String(), nullable=True)
    )
    op.execute("UPDATE released_agent_versions SET arch='x86_64';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("released_agent_versions", "arch")
    op.drop_column("released_agent_versions", "osquery_hash_md5")
    op.drop_column("released_agent_versions", "cpt_version")
    op.drop_column("released_agent_versions", "cpt_hash_md5")
    # ### end Alembic commands ###
