"""empty message

Revision ID: 67ede2878785
Revises: d02aae3a1aba
Create Date: 2020-07-16 14:50:46.454585

"""

# revision identifiers, used by Alembic.
revision = "67ede2878785"
down_revision = "cf177f7d6eff"

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
