"""empty message

Revision ID: 956e1ee74895
Revises: c69c177cbe2d
Create Date: 2021-12-22 13:48:46.547441

"""

# revision identifiers, used by Alembic.
revision = '956e1ee74895'
down_revision = 'c69c177cbe2d'

from alembic import op
import sqlalchemy as sa
# import polylogyx.db.database

from sqlalchemy.dialects import postgresql


def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('alerts_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alerts_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("update settings set name='data_retention_days' where name='purge_data_duration'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("update settings set name='purge_data_duration' where name='data_retention_days'")
    op.drop_table('analyst_notes')
    # ### end Alembic commands ###
