"""empty message

Revision ID: 95a0deb3919d
Revises: 90988dd06a28
Create Date: 2022-07-08 17:51:14.434297

"""

# revision identifiers, used by Alembic.
revision = '95a0deb3919d'
down_revision = '90988dd06a28'

from alembic import op
import sqlalchemy as sa
import polylogyx.db.database
import flask_authorize

from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        update rule set  severity = 'MEDIUM' where severity='WARNING'
        ''')

    op.execute('''
        update alerts set  severity = 'MEDIUM' where severity='WARNING'
        ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
