"""empty message

Revision ID: c69c177cbe2d
Revises: c78975eaf294
Create Date: 2021-12-13 11:45:50.860785

"""

# revision identifiers, used by Alembic.
revision = 'c69c177cbe2d'
down_revision = '0c39eb9a5b6a'

from alembic import op
import sqlalchemy as sa
import polylogyx.db.database
from sqlalchemy.dialects import postgresql

def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('result_log_scan', sa.Column('vt_updated_at', sa.DateTime(), nullable=True))
    op.execute("update result_log_scan set vt_updated_at=created_at;")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('result_log_scan', 'vt_updated_at')

    # ### end Alembic commands ###
