"""empty message

Revision ID: c78975eaf294
Revises: c0379b846404
Create Date: 2021-07-21 02:21:26.911493

"""

# revision identifiers, used by Alembic.
revision = 'c78975eaf294'
down_revision = 'c0379b846404'

from alembic import op
import sqlalchemy as sa
import polylogyx.db.database
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('result_log_maps',
    sa.Column('result_log_id', sa.Integer(), nullable=True),
    sa.Column('result_log_scan_id', sa.Integer(), nullable=True),
        # sa.ForeignKeyConstraint(['result_log_id'], ['result_log.id' ]),
    sa.ForeignKeyConstraint(['result_log_scan_id'], ['result_log_scan.id'], )
    )
    op.create_index(op.f('idx_result_log_maps_result_log_scan_id'), 'result_log_maps', ['result_log_scan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('idx_result_log_maps_result_log_scan_id'), table_name='result_log_maps')
    op.drop_table('result_log_maps')

    # ### end Alembic commands ###
