"""empty message

Revision ID: ccbbec237ccd
Revises: 2ff330668729
Create Date: 2020-12-01 18:27:20.436671

"""

# revision identifiers, used by Alembic.
revision = "ccbbec237ccd"
down_revision = "2ff330668729"

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
