"""empty message

Revision ID: d02aae3a1aba
Revises: 352f4b476585
Create Date: 2020-07-07 13:02:50.604183

"""

# revision identifiers, used by Alembic.
revision = "d02aae3a1aba"
down_revision = "352f4b476585"

import json

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
