"""empty message

Revision ID: daed9343771c
Revises: ccbbec237ccd
Create Date: 2021-01-29 15:37:59.111636

"""

# revision identifiers, used by Alembic.
revision = "daed9343771c"
down_revision = "ccbbec237ccd"

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_alert_log_alert_id", "alert_log", ["alert_id"], unique=False)
    op.execute(
        "CREATE INDEX idx_result_log_on_columns_eventid ON result_log  USING BTREE((columns->> 'eventid'));"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_alert_log_alert_id", table_name="alert_log")
    op.drop_index("idx_result_log_on_columns_eventid", table_name="result_log")
    op.drop_index("idx_result_log_on_columns_source", table_name="result_log")
    # ### end Alembic commands ###
